version: '3.8'

services:
  mysql-bookserver:
    container_name: bookserver_mysql
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=bookserver
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=bookserver
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:


